events/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r"create_parkour/$", views.ParkourCreateView.as_view(), name="create_parkour"),
    url(r"parkour/(?P<pk>\d+)/$", views.ParkourDetailView.as_view(), name="parkour_detail"),
    url(r"parkours/$", views.PastParkoursListView.as_view(), name="parkour_list"),
    url(r"^search/$", views.search,name="parkour_search"),
]

sonoriproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', auth_views.login, name="login"),
    url(r'^accounts/logout/$', auth_views.logout, {'template_name': 'logout.html', 'next_page': '/login'},  name="logout"),
    url(r'^accounts/signup/$', views.SignupView.as_view(),  name="signup"),
    url(r'^accounts/profile/$', views.UserProfileView.as_view(), name="profile"),
    url(r'^users/$', views.UserListView.as_view(), name="users"),
    url(r'^user/(?P<pk>\d+)/$', views.PublicProfileView.as_view(), name="public_profile"),
    url(r'^events/', include('events.urls', namespace="events")),
    url(r'^$', views.HomeView.as_view(), name="home"),
]

urlpatterns += staticfiles_urlpatterns()

events/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User


class Event(models.Model):
    title = models.CharField(max_length=50)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    created_at = models.DateTimeField(auto_now=True)
    competitors = models.ManyToManyField(User, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        abstract = True
        ordering = ['-date',]


class ParkourEvent(Event):
    description = models.TextField()
    is_active = models.BooleanField(default=True)

    def get_absolute_url(self):
                    #namespace:func_name
        return reverse("events:parkour_detail", kwargs={"pk":self.pk})


class RunningEvent(Event):
    pass

events/forms.py
from django import forms

from . import models

class ParkourEventForm(forms.ModelForm):

    ### I've customized the classes of the field in another way (ln. 28)
    ### but i'll keep this line as a reference
    # date = forms.DateField(widget=forms.DateInput(attrs={"class": "datepicker form-control"}))

    class Meta:
        model = models.ParkourEvent
        fields = [
            "title",
            "description",
            "date",
            "time",
        ]

        # labels = {
        #     "time":"Zaman"
        # }

        placeholders = {
            "time": "H:M"
        }

        widgets = {
                # ## It may not be the correct approach to do attrs in here
                # ## But is definately the easier one at the moment. 
                # Check parkour_create.html
            "date": forms.DateInput(attrs={"class": "datepicker form-control"})
        }

sonoriproject/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    class Meta:
        # fields = ("username", "email", "password1", "password2")
        model = User
        fields = UserCreationForm.Meta.fields + ("first_name",)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Nickname"
        self.fields["first_name"].label = "First Naaamoo"

events/views.py
from django import forms
from django.views import generic
from django.db.models import Q
from django.shortcuts import redirect, reverse, render
from django.core.urlresolvers import reverse_lazy
from django.contrib.admin import widgets

from braces.views import StaffuserRequiredMixin, LoginRequiredMixin

from . import models
from . import forms

class ParkourCreateView(LoginRequiredMixin, StaffuserRequiredMixin, generic.CreateView):
    model = models.ParkourEvent
    template_name = "events/parkour_create.html"
    form_class = forms.ParkourEventForm


##
## This view handles all AddUser-RemoveUser action on ParkourEvent
##
class ParkourDetailView(generic.DetailView):
    model = models.ParkourEvent
    template_name = "events/parkour_detail.html"

    ## i can delete this override, but i want to test if i user p.._related
    ## correct and it actually does something
    ## but i'm too lazy to install the toolbar for that
    def get_query_set(self):
        return self.model.objects.prefetch_related('competitors').all()

    ## process your request and
    ## redirects you where the fuck you come from
    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            pmodel = models.ParkourEvent.objects.get(pk=kwargs["pk"])
            if (request.user in pmodel.competitors.all()) and request.POST.get("remove"):
                pmodel.competitors.remove(request.user)
            elif (request.user not in pmodel.competitors.all()) and request.POST.get("add"):
                pmodel.competitors.add(request.user)
                # return redirect(pmodel)
            # return redirect(pmodel)
            print(self.request.user.pk)
            return redirect(request.META["HTTP_REFERER"])
        else:
            # redirect(pmodel)
            return redirect(request.META["HTTP_REFERER"])

class PastParkoursListView(generic.ListView):
    template_name = "events/parkour_list.html"

    ## by default context_object_name = *modelname*_list
    context_object_name = "parkours"

    ## we can directly define a modal or query_set i guess
    ## but well... this works too, overriding stuff
    def get_queryset(self):
        return models.ParkourEvent.objects.filter()


def search(request):
    # gets the value of input box named "q"
    term = request.GET.get("q")
    # "i"contains. that i means make this case insensitive
    parkours = models.ParkourEvent.objects.filter(
        # tihs way we can search both titles and desc.s without them interrupting
        # each other. Q objects are entire queries on their own
        Q(title__icontains=term) | Q(description__icontains=term) | Q(date__icontains=term) )
    return render(request, "events/parkour_list.html", {"parkours": parkours})

sonoriproject/views.py
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.models import User

# from django.contrib.auth.forms import UserCreationForm
from . import forms


## UserCreationFrom is a default modelform provided by auth module
## to make usercreation easily. we however modiefied it a bit in forms.py
## and will use it to have control on things
class SignupView(generic.CreateView):
    # form_class = UserCreationForm
    ## We use modified version of UserCreationForm
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class UserListView(generic.ListView):
    ## for user in object_list print user
    ## this is how listview rolls in template
    model = User
    template_name = "user_list.html"

## User's edit profile view
class UserProfileView(generic.DetailView, generic.UpdateView):
    fields = ("username", "first_name", "last_name", "email")
    template_name = "user_profile.html"
    success_url = "/accounts/profile"

    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.pk)

class PublicProfileView(generic.DetailView):
    template_name = "public_profile.html"
    model = User

class HomeView(View):

    def get(self, request):
        return render(request, "home.html")

events/templates/events/parkour_create.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">
    <h1>Parkour Create</h1>
    <form method="post" class="form well .form-group" >
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class="btn btn-default">
    </form>
</div>
{% endblock %}


{% block endscript %}
    <script src="{% static 'assets/js/bootstrap-datepicker.js' %}" charset="utf-8"></script>
    <script type="text/javascript">
        a = document.getElementsByName("time")[0];
        a.placeholder = "H:M";
    </script>
{% endblock %}

events/templates/events/parkour_detail.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">
    <div class="panel panel-default">
        <div class="panel-heading"><a href="{% url 'events:parkour_detail' pk=parkourevent.pk %}">{{parkourevent.title}}</a></div>
        <div class="panel-body">
            {{parkourevent.description}}
            <table class="table table-responsive">
                <thead>
                    <th>#</th>
                    <th>username</th>
                    <th>email</th>
                </thead>
                <tbody>
                    {% for user in parkourevent.competitors.all %}
                    <tr>
                        <td></td>
                        <td>{{user.username}}</td>
                        <td>{{user.email}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>


        {% if user not in parkourevent.competitors.all %}
        <form method='POST'>
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" name="add" value="Add">
        </form>
        {% else %}
        <form method='POST'>
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" name="remove" value="Remove">
        </form>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

events/templates/events/parkour_list.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">
  <form id="searchform" action="{% url 'events:parkour_search' %}" method="get" accept-charset="utf-8">
      <button class="searchbutton" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
      <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Search">
    </form>
    {% for parkourevent in parkours %}
        <div class="panel panel-default">
        <div class="panel-heading"><a href="{% url 'events:parkour_detail' pk=parkourevent.pk %}">{{parkourevent.title}}</a></div>
            <div class="panel-body">
                {{parkourevent.description}}
                <table class="table table-responsive">
                    <thead>
                        <th>#</th>
                        <th>username</th>
                        <th>email</th>
                    </thead>
                    <tbody>
                        {% for user in parkourevent.competitors.all %}
                        <tr>
                            <td></td>
                            <td>{{user.username}}</td>
                            <td>{{user.email}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% if parkourevent.is_active %}
                    {% if user not in parkourevent.competitors.all %}
                    <form method='POST' action="{% url 'events:parkour_detail' pk=parkourevent.pk %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" name="add" value="Add">
                    </form>
                    {% else %}
                    <form method='POST' action="{% url 'events:parkour_detail' pk=parkourevent.pk %}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" name="remove" value="Remove">
                    </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>

    {% endfor %}
</div>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">
    Home
</div>
{% endblock %}

templates/layout.html
{% load bootstrap3 %}
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    {# Load the tag library #}
    {% bootstrap_css %}
    <link href="{% static 'assets/css/ct-paper.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
    <title></title>
</head>

<body>
    {% include "navbar.html" %}

    {% bootstrap_messages %}

    {% block body_content %} {% endblock %}

    <script src="{% static 'assets/js/jquery-1.10.2.js' %}" charset="utf-8"></script>
    {% bootstrap_javascript %}
    <script src="{% static 'assets/js/ct-paper.js' %}" charset="utf-8"></script>
    {% block endscript %}{% endblock %}
</body>

</html>

templates/navbar.html
{% block navbar %}
<div id="navbar">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button> <a class="navbar-brand" href="/">Djanbela</a> </div>
            <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li> <a href="{% url 'events:parkour_list' %}">Parkours</a> </li>
                    <li class="active"> <a href="{% url 'users' %}">Team List</a> </li>
                    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li> <a href="#">Action</a> </li>
                            <li> <a href="#">Another action</a> </li>
                            <li> <a href="#">Something else here</a> </li>
                            <li class="divider"></li>
                            <li> <a href="#">Separated link</a> </li>
                            <li class="divider"></li>
                            <li> <a href="#">One more separated link</a> </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

templates/public_profile.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">

    <div class="panel panel-default">
        <div class="panel-heading">{{user.username}}'s Profile</div>
        <div class="panel-body">
        <ul>
            <li>Name: {{user.first_name}} {{user.last_name}}</li>
            <li>Date Joined: {{user.date_joined}}</li>
            <li>Email: {{user.email}}</li>
        </ul>
            Total Parkours: {{user.parkourevent_set.all.count}}
            Total Runs: {{user.runningevent_set.all.count}}
            <br>
        </div>
    </div>
</div>
{% endblock %}

templates/user_list.html
{% extends "layout.html" %}

{% block body_content %}
<div class="container-fluid">
<table class="table table-responsive">
    <thead>
        <th>Username</th>
        <th>Name</th>
        <th>Joined at</th>
        <th>Email</th>
        <th>Is Staff</th>
    </thead>
    <tbody>
        {% for member in object_list %}
            <tr class="active">
                <td><a href="{% url 'public_profile' pk=member.pk %}">{{ member.username }}</a></td>
                <td>{{member.first_name}} {{member.last_name}}</td>
                <td>{{member.date_joined}}</td>
                <td>{{member.email}}</td>
                <td>{{member.is_staff}}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}

templates/user_profile.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% load static from staticfiles %}

{% block body_content %}
<div class="container-fluid">

    <div class="panel panel-default">
        <div class="panel-heading">{{user.username}}'s Profile</div>
        <div class="panel-body">
            <form method='POST'>
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Save">
            </form>
            Total Parkours: {{user.parkourevent_set.all.count}}
            Total Runs: {{user.runningevent_set.all.count}}
            <br>
        </div>
    </div>
</div>
{% endblock %}